services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    command: >
      sh -c "npm install && node server.js"
    ports:
      - 8080:3000
    expose:
      - 8080
    environment:
      - API_URI=http://topics-api:5000/api/topics
    depends_on:
      - backend
  backend:
    container_name: topics-api
    build:
      context: ./backend
    command: >
      sh -c "npm install && npm start"
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      - DATABASE_URL=mongodb://some-mongo:27017
      - DATABASE_NAME=TopicstoreDb
      - HOST=topics-api
      - PORT=5000
    depends_on:
      - mongodb
  mongodb:
    container_name: some-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_SERVER="some-mongo"
      - ME_CONFIG_BASICAUTH_USERNAME="user"
      - ME_CONFIG_BASICAUTH_PASSWORD="password"
    volumes:
      - type: bind
        source: ./data
        target: $HOME/mongo/data
      - type: bind
        source: ./database/data/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
networks:
  lemoncode-challenge:
