services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    environment:
      - API_URI=http://topics-api:5000/api/topics
    depends_on:
      - backend
  backend:
    container_name: topics-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=mongodb://some-mongo:27017
      - DATABASE_NAME=TopicstoreDb
      - HOST=topics-api
      - PORT=5000
    depends_on:
      - mongodb
  mongodb:
    container_name: some-mongo
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_MONGODB_SERVER="some-mongo"
      - ME_CONFIG_BASICAUTH_USERNAME="user"
      - ME_CONFIG_BASICAUTH_PASSWORD="password"
    volumes:
      - mongodata:/data/db
networks:
  lemoncode-challenge:
volumes:
  mongodata:
