version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
networks:
  lemoncode-challenge:
