apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-11-21T20:40:26Z"
  labels:
    app: load-balancer
  name: load-balancer
  namespace: default
  resourceVersion: "2144"
  uid: 5e030a51-a6cd-4865-a908-acd1d33ecc80
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.117.74
  clusterIPs:
  - 10.100.117.74
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 3000-3000
    nodePort: 32661
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: load-balancer
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
