apiVersion: v1
kind: Pod
metadata:
  name: todo-app
  labels:
    name: todo-app
spec:
  containers:
    - name: todo-app
      image: node:12-alpine3.12
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3001
