pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checkout..'
                    git branch: 'master',
                    url: 'https://github.com/Lemoncode/bootcamp-devops-lemoncode.git'
            }
        }
        stage('Compile') {
            environment {
                GRADLE_VERSION='6.6.1'
                GRADLE_BASE_URL='https://services.gradle.org/distributions'
                GRADLE_SHA='7873ed5287f47ca03549ab8dcb6dc877ac7f0e3d7b1eb12685161d10080910ac'
            }
            steps {
                echo 'Compiling..'
                dir('/var/jenkins_home/workspace/solucion-ci/03-cd/exercises/jenkins-resources/calculator') {
                    sh 'ls -l && ./gradlew compileJava'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                echo 'Testing....'
                // sh 'gradle test'
            }
        }
    }
}